### ISSUE TITLE
在训练时  显示没有定义这个字典里的key    

### ISSUE THREAD

**Issue by Liurongfen** [bachzz/UW-DiffPhys#2]
(DiffPhys) PS E:\LRF\UW-DiffPhys-main\UW-DiffPhys-main> python train_UW-DDIM.py --config underwater_lsui_uieb_128.yml --resume ckpts/LSUI_UIEB_ddpm.pth.tar
Using device: cuda
=> using dataset 'LSUI_UIEB'
Traceback (most recent call last):
  File "E:\LRF\UW-DiffPhys-main\UW-DiffPhys-main\train_UW-DDIM.py", line 75, in <module>
    main()
  File "E:\LRF\UW-DiffPhys-main\UW-DiffPhys-main\train_UW-DDIM.py", line 66, in main
    DATASET = datasets.__dict__["Underwater"](config)
KeyError: 'Underwater'

在训练时  显示没有定义这个字典里的key

**Comment by bachzz** [comment]
Could you try again with the updated dataset loader file
